[settings]
class = "Abis"
menuOrder = 20
doc_group = "001-Route"
doc_descr = "a human-readable representation of a Solidity smart contract"
doc_route = "200-abis"
attributes = ""
produced_by = "abis"
contains = "function"
store_type = "chain-scoped"
disable_go = false

[[facets]]
name = "Downloaded"
store = "Abis"
actions = ["autoname", "remove","export"]
viewType = "table"

[[facets]]
name = "Known"
store = "Abis"
actions = ["export"]
viewType = "table"

[[facets]]
name = "Functions"
store = "Functions"
actions = ["export"]
viewType = "table"

[[facets]]
name = "Events"
store = "Functions"
actions = ["export"]
viewType = "table"
