[settings]
    class = "AddressList"
    doc_group = "001-Route"
    doc_descr = "A list off addresses inside a project"
    doc_route = "001-addresslist"
    attributes = ""
    produced_by = "addresslist"
    disable_go = true
