[settings]
class = "Chunks"
menuOrder = 40
menuLabel = "Unchained"
doc_group = "001-Route"
doc_descr = "internal-use only data model detailing a single index chunk file"
doc_route = "400-chunks"
attributes = ""
produced_by = "chunks"
store_type = "chain-scoped"
disable_go = false

[[facets]]
name = "Stats"
store = "Stats"
actions = ["export"]
viewType = "table"
panel = "custom"
panelChart = true

[[facets]]
name = "Index"
store = "Index"
actions = ["export"]
viewType = "table"
panel = "custom"
panelChart = true

[[facets]]
name = "Blooms"
store = "Blooms"
actions = ["export"]
viewType = "table"
panel = "custom"
panelChart = true

[[facets]]
name = "Manifest"
store = "Manifest"
viewType = "form"

