[settings]
class = "Comparitoor"
menuOrder = 80
doc_group = "001-Comparisons"
doc_descr = "Compare transactions across multiple sources for a given address"
doc_route = "800-comparitoor"
attributes = ""
produced_by = "comparitoor"
disable_go = false

[[facets]]
name = "Comparitoor"
store = "Transaction"
actions = ["export"]
viewType = "custom"

[[facets]]
name = "Chifra"
store = "Transaction"
actions = ["export"]
viewType = "table"

[[facets]]
name = "Etherscan"
store = "Transaction"
actions = ["export"]
viewType = "table"

[[facets]]
name = "Covalent"
store = "Transaction"
actions = ["export"]
viewType = "table"

[[facets]]
name = "Alchemy"
store = "Transaction"
actions = ["export"]
viewType = "table"
