[settings]
class = "Dresses"
menuOrder = 70
doc_group = "001-Route"
doc_descr = "multi-facet generative art collection for DalleDress"
doc_route = "700-dresses"
attributes = ""
produced_by = "dresses"
disable_go = false

[[facets]]
name = "Generator"
store = "dalle.DalleDress"
actions = [""]
viewType = "custom"
navigate = "dresses|gallery|address|original"

[[facets]]
name = "Series"
store = "dalle.Series"
viewType = "custom"
actions = ["update","create","delete","remove","export"]
mapKey = "item.Suffix"

[[facets]]
name = "Databases"
store = "dalle.Databases"
actions = ["export"]
viewType = "custom"
navigate = "dresses|items|databaseName|databaseName"

[[facets]]
name = "Items"
store = "model.Items"
actions = ["export"]
viewType = "custom"

[[facets]]
name = "Events"
store = "Logs"
actions = ["export"]
viewType = "table"
needsCalcs = true

[[facets]]
name = "Gallery"
store = "dalle.DalleDress"
actions = ["export"]
viewType = "custom"
navigate = "dresses|generator|address|original"
mapKey = "item.Original + \":\" + item.AnnotatedPath"
