[settings]
class = "Exports"
doc_group = "001-Route"
doc_descr = "internal-use only data model detailing a single index chunk file"
doc_route = "100-exports"
attributes = ""
produced_by = "exports"
disable_go = false

[[facets]]
name = "Statements"
store = "Statements"
actions = ["export"]
renderer = "panel"
needsCalcs = true
mapKey = "item.Asset.Hex()"

[[facets]]
name = "Balances"
store = "Balances"
actions = ["export"]

[[facets]]
name = "Transfers"
store = "Transfers"
actions = ["export"]

[[facets]]
name = "Transactions"
store = "Transactions"
actions = ["export"]

[[facets]]
name = "OpenApprovals"
store = "OpenApprovals"
actions = ["export"]
renderer = "panel"

[[facets]]
name = "ApprovalLogs"
store = "ApprovalLogs"
actions = ["export"]

[[facets]]
name = "ApprovalTxs"
store = "ApprovalTxs"
actions = ["export"]

[[facets]]
name = "Withdrawals"
store = "Withdrawals"
actions = ["export"]

[[facets]]
name = "Assets"
store = "Assets"
actions = ["export"]
mapKey = "item.Asset.Hex()"
useMapKey = true
needsCalcs = true
renderer = "panel"
panelChart = true

[[facets]]
name = "AssetCharts"
store = "Statements"
actions = ["export"]
renderer = "facet"
viewType = "canvas"
facetChart = true
needsCalcs = true
mapKey = "item.Asset.Hex()"

[[facets]]
name = "Logs"
store = "Logs"
actions = ["export"]
needsCalcs = true

[[facets]]
name = "Traces"
store = "Traces"
actions = ["export"]

[[facets]]
name = "Receipts"
store = "Receipts"
actions = ["export"]

