[settings]
    class = "Projects"
    doc_group = "001-Route"
    doc_descr = "project management and home dashboard for the TrueBlocks Explorer"
    doc_route = "001-projects"
    attributes = ""
    produced_by = "projects"
    disable_go = false

[[facets]]
    name = "Manage"
    store = "project.Projects"
    actions = []

[[facets]]
    name = "Projects"
    store = "project.AddressList"
    actions = []
