[settings]
class = "Projects"
menuOrder = 1
doc_group = "001-Route"
doc_descr = "project management and home dashboard"
doc_route = "001-projects"
attributes = ""
produced_by = "projects"
disable_go = false

[[facets]]
name = "Manage"
store = "project.Projects"
actions = []
viewType = "custom"

[[facets]]
name = "Projects"
store = "project.AddressList"
actions = []
viewType = "custom"
isDynamic = true
navigate = "exports|<latest>|address|address"
